name: Smoke test "ctf" build

on: 
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    paths:
      - src/ctf/**
      - .github/workflows/smoke-ctf.yaml
      # - .github/actions/**
      # - build/**

env:
  image: ctf

jobs:
  smoke-test:
    name: Smoke test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v3

    - name: Build image
      id: build_image
      shell: bash
      run: |
        IMAGE="${{ env.image }}"
        
        set -e

        export DOCKER_BUILDKIT=1
        echo "(*) Installing @devcontainer/cli"
        npm install -g @devcontainers/cli

        echo "(*) Building image - ${IMAGE}"
        id_label="test-container=${IMAGE}"
        devcontainer up --id-label ${id_label} --workspace-folder "src/${IMAGE}/"

    - name: Test image
      id: test_image
      shell: bash
      run: |
        IMAGE="${{ env.image }}"
        
        export DOCKER_BUILDKIT=1
        set -e

        echo "(*) Running test..."
        id_label="test-container=${IMAGE}"

        echo "(*) Docker image details..."
        docker images

        docker rm -f $(docker container ls -f "label=${id_label}" -q)